package de.netzmuffel.bank.model.enumerator;

import javax.swing.JOptionPane;

import de.netzmuffel.bank.Config;
import de.netzmuffel.bank.localization.Displayable;
import de.netzmuffel.bank.localization.I18n;

public enum Error implements Displayable {
	APPLICATION_CONFIGURATION_FILE_CANNOT_CREATE, APPLICATION_DATABASE_CONNECT_EXISTING_DATABASE, APPLICATION_DATABASE_CONNECT_NEW_DATABASE, APPLICATION_UIMANAGER_CANT_SET, APPLICATION_DATABASE_CONNECT_TESTDATABASE, APPLICATION_BOOLEAN_CONVERSION_EXCEPTION,

	CONFIGURATION_CANNOT_READ_CONFIGFILE, CONFIGURATION_CANNOT_FIND_OFFLINEFILE, CONFIGURATION_CANNOT_READ_VERSION_FROM_WEBFILE, CONFIGURATION_WRONG_URL_WEBFILE, CONFIGURATION_SAVE_THE_PROPERTY, CONFIGURATION_CANNOT_WRITE_IN_VERSIONFILE, CONFIGURATION_OFFLINEVERSION_NOT_INTEGER, CONFIGURATION_OFFLINEVERSION_NO_INTEGER_FOUND,

	COURSEADDEDIT_COURSE_ALREADY_EXIST, COURSEADDEDIT_UPDATE_GET_COURSE, GENERAL_NOTEXTINFIELD, COURSEADDEDIT_CREATE_OR_UPDATE_COURSE, COURSEADDEDIT_FILL_COMBOBOX,

	COURSEGRADESREMOVE_TOPIC_REMOVE,

	COURSEGRADESSTUDENTEDIT_GRADES_REFRESH,

	COURSEGRADESTOPICADDEDIT_TOPIC_CREATE_OR_UPDATE,

	COURSESTUDENT_ADDEXISTS_CANNOT_QUERY, COURSESTUDENT_ADDEXISTS_CREATE, COURSESTUDENT_EDIT_CREATE_OR_UPDATE,

	SETTINGS_CANCEL_APPLY, SETTINGS_DATABASE_SHUTDOWN, SETTINGS_DATABASE_ENCRYPT, SETTINGS_DATABASE_DECRYPT, SETTINGS_CONFIG_FILE_LOCKED,

	START_CHECK_TEACHER_EXISTS, START_DELETE_SELECTED_COURSE, START_OPEN_TAB_FOR_SELECTED_COURSE,

	STUDENTMANAGER_DELETE_STUDENT,

	TABLEMODEL_SHOWCOURSES_GETVALUEAT_STUDENTCOUNT, TABLEMODEL_SHOWCOURSES_REFRESH,

	TABLEMODEL_SHOWGRADES_GETGRADE_QUERY, TABLEMODEL_SHOWGRADES_REFRESH, TABLEMODEL_SHOWGRADES_SETVALUEAT_GRADE_UPDATE, TABLEMODEL_SHOWGRADES_SETVALUEAT_NOVALIDVALUE, TABLEMODEL_SHOWGRADES_SETVALUEAT_TOPIC_UPDATE,

	TABLEMODEL_SHOWSTUDENTS_REFRESH,

	TEACHERADDEDIT_CREATEORUPDATE, TEACHERMANAGER_TEACHER_EXISTS, TEACHERMANAGER_TEACHER_REMOVE,

	UPDATE_CANNOT_START_UPDATER, UPDATE_CANNOT_DOWNLOAD_UPDATER,

	START_DATABASE_FILE_NOT_ACCESSABLE, DATABASE_FILE_NOT_FOUND, DATABASE_CANNOT_CLOSE_CONNECTION;

	private int code;
	private String description;

	Error() {
		this.code = this.ordinal();
		this.description = I18n.getEnumText(this);
	}

	public void showDialog() {
		this.showErrorInLog();
		JOptionPane.showMessageDialog(null, I18n.get().errorOccured(this.code, this.description), I18n.get().error(),
				JOptionPane.ERROR_MESSAGE);
	}

	public void showErrorInLog() {
		Config.logger.error("An error occurred with Code {} [{}]", this.code, this);
	}

	public void showDialog(Exception e) {
		this.showDialog();
		e.printStackTrace();
	}
}
